### ISSUE TITLE
Cannot read property then of undefined

### ISSUE THREAD

**Issue by abelardolg** [isaacs/node-mkdirp#31]
Hi there,

This is where I use your package:

```
function savePost(req, res, next) {
    let userFile = req.files.file;
    // Use the mv() method to place the file somewhere on your server
    mkdirp('files')
        .then( made => { // Here, it gives that error : cannot read property of undefined
            userFile.mv('src/files/upload/' + userFile.name , function (err) {
                console.log(err);
                if (err)
                    return res.status(500).send(err);

                res.send('File uploaded!');
            });
        })
    .catch(error => console.error(error));
}
```

Directories were created with no problem

Using version     "mkdirp": "^0.5.5",
On Ubuntu 20

Best regards.

**Comment by abelardolg** [comment]
I inspected your source and I realized of the following (the below numbers indicate the line):

7: For `function mkdirP (p, opts, f, made) `, I only provide 1 argument; `opts`, `f` and `made` aren't provided by me.
26: ` var cb = f || function () {};`: `f` is `undefined` and therefore `cb` is an anonymous function (with no body).
54: `cb(null, made)` is invoked...but this function has not body 🤔.

I think is the reason what `undefined` is returned.

**Comment by wil93** [comment]
I just had the same issue.

The documentation says `mkdirp(dir, [opts]) -> Promise<String | undefined>`

That seems to *not be the case*, since mkdir can definitely also return `undefined`, without any Promise around it.

I'm surprised that such a popular library has such a blatant error in either implementation or documentation.

---

I solved this by switching to a better library: https://github.com/sindresorhus/make-dir

**Comment by isaacs** [comment]
This has been fixed.

The 0.5 version was a year out of supported status when this issue was posted.
